apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello-spring
  namespace: hello
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: hello-spring-token
  namespace: hello
  annotations:
    kubernetes.io/service-account.name: "hello-spring"
---
apiVersion: v1
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: read-only
rules:
- apiGroups:
    - apps
    - extensions
    - "*"
    - ""
  resources: ["*"]
  verbs: ["get", "watch", "list"]
---
apiVersion: v1
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hello-spring
subjects:
- kind: ServiceAccount
  name: hello-spring
  namespace: hello
- kind: User
  name: hello-spring
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: read-only
  apiGroup: rbac.authorization.k8s.io